version: '3.5'

services:

  redis:
    image: redis@sha256:09c33840ec47815dc0351f1eca3befe741d7105b3e95bc8fdb9a7e4985b9e1e5
    network_mode: host

  vdns:
    depends_on:
      - redis
    build: .
    environment:
      DEBUG: "yes"
      NODE_HEALTHY_FILENAME: /opt/healthz/node
    network_mode: host
    volumes:
      - healthz:/opt/healthz

  nginx:
    depends_on:
      - vdns
    build: nginx
    network_mode: host
    environment:
      METRIC_LUA_WITH_HOST: "yes"
      # ENABLE_ACCESS_LOG: "yes"
    volumes:
      - healthz:/opt/healthz

  test:
    image: nginx:alpine
    ports:
      - "8080:80"

volumes:
  healthz:
