{{ if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: cwm-worker-ingress
spec:
  ports:
  - name: "80"
    port: 80
  - name: "443"
    port: 443
  selector:
    app: cwm-worker-ingress
{{ end }}
