{{ if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: cwm-worker-ingress-https
  {{ if .Values.namespace }}namespace: {{ .Values.namespace | quote }}{{ end }}
spec:
  ports:
  - name: "443"
    port: 443
  selector:
    app: cwm-worker-ingress-https
{{ end }}
