{{ if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: cwm-worker-ingress-http
  {{ if .Values.namespace }}namespace: {{ .Values.namespace | quote }}{{ end }}
spec:
  ports:
  - name: "80"
    port: 80
  selector:
    app: cwm-worker-ingress-http
{{ end }}
