FROM nginx:mainline@sha256:b0ad43f7ee5edbc0effbc14645ae7055e21bc1973aee5150745632a24a752661
COPY nginx.conf resolver.conf http_listen.conf https_listen.conf extra-pre.conf extra-post.conf /etc/nginx/
