debug: false
replicas: 1
revisionHistoryLimit: 2
terminationGracePeriodSeconds: 5
updateStrategy: |
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
imagePullSecrets: |
  - name: github
#tolerations: []

nginx:
  image: docker.pkg.github.com/cloudwebmanage/cwm-worker-ingress/nginx
  tag: ""
  imagePullPolicy: IfNotPresent
  resources: |
    requests:
      cpu: .1
      memory: 50Mi
    limits:
      memory: 200Mi

vdns:
  image: docker.pkg.github.com/cloudwebmanage/cwm-worker-ingress/vdns
  tag: ""
  imagePullPolicy: IfNotPresent
  resources: |
    requests:
      cpu: .1
      memory: 100Mi
    limits:
      memory: 200Mi
  redisHost: localhost
  redisPort: "6379"
  redisWriteHost: redis
  redisWritePort: "6379"
  debugVerbosity: "1"
  waitForDomainAvailabilityRefreshSeconds: "0.01"
  waitForDomainAvailabilityMaxWaitSeconds: "5"
  mainProcessRefreshSeconds: "0.1"
  prometheusMetricsPort: "8080"
  prometheusMetricsWithDomainLabel: false

redis:
  image: redis@sha256:09c33840ec47815dc0351f1eca3befe741d7105b3e95bc8fdb9a7e4985b9e1e5
  imagePullPolicy: IfNotPresent
  resources: |
    requests:
      cpu: .05
      memory: 50Mi
    limits:
      memory: 200Mi

service:
  enabled: true
