name: CI
on:
  push:
jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PACKAGES_READER_GITHUB_TOKEN: ${{ secrets.PACKAGES_READER_GITHUB_TOKEN }}
        PACKAGES_READER_GITHUB_USER: ${{ secrets.PACKAGES_READER_GITHUB_USER }}
      run: |
        sudo apt-get install -y python3-venv redis-tools &&\
        python3 -m venv venv &&\
        venv/bin/python3 -m pip install --upgrade pip &&\
        venv/bin/python3 -m pip install --upgrade setuptools wheel &&\
        venv/bin/python -m pip install -r requirements.txt &&\
        venv/bin/python -m pip install -e . &&\
        docker run -d --rm --name redis -p 6379:6379 redis
        [ "$?" != "0" ] && echo failed to initialize for tests && exit 1
        while ! redis-cli ping; do sleep 1; done
        DEBUG=yes REDIS_HOST=172.17.0.1 venv/bin/cwm_worker_ingress vdns 10053 >log.txt 2>&1 &
        echo 172.17.0.1 cwm-worker-test.com | sudo tee -a /etc/hosts &&\
        . venv/bin/activate &&\
        timeout -k 60s 60s ./run_tests.sh
        TESTS_RES=$?
        echo TESTS_RES=$TESTS_RES
        echo "-- vdns server log --"
        cat log.txt
        echo "-- vdns server metrics --"
        cat .metrics
        [ "${TESTS_RES}" != "0" ] && echo tests failed && exit 1
        echo "${GITHUB_TOKEN}" | docker login https://docker.pkg.github.com -u cloudwebmanage --password-stdin &&\
        docker pull docker.pkg.github.com/cloudwebmanage/cwm-worker-ingress/vdns:latest &&\
        docker pull docker.pkg.github.com/cloudwebmanage/cwm-worker-ingress/nginx:latest &&\
        docker build -t vdns --cache-from docker.pkg.github.com/cloudwebmanage/cwm-worker-ingress/vdns:latest . &&\
        docker build -t nginx --cache-from docker.pkg.github.com/cloudwebmanage/cwm-worker-ingress/nginx:latest nginx &&\
        docker tag vdns docker.pkg.github.com/cloudwebmanage/cwm-worker-ingress/vdns:$GITHUB_SHA &&\
        docker tag nginx docker.pkg.github.com/cloudwebmanage/cwm-worker-ingress/nginx:$GITHUB_SHA &&\
        docker push docker.pkg.github.com/cloudwebmanage/cwm-worker-ingress/vdns:$GITHUB_SHA &&\
        docker push docker.pkg.github.com/cloudwebmanage/cwm-worker-ingress/nginx:$GITHUB_SHA &&\
        if [ "${GITHUB_REF}" == "refs/heads/master" ]; then
          docker tag vdns docker.pkg.github.com/cloudwebmanage/cwm-worker-ingress/vdns:latest &&\
          docker tag nginx docker.pkg.github.com/cloudwebmanage/cwm-worker-ingress/nginx:latest &&\
          docker push docker.pkg.github.com/cloudwebmanage/cwm-worker-ingress/vdns:latest &&\
          docker push docker.pkg.github.com/cloudwebmanage/cwm-worker-ingress/nginx:latest &&\
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl" &&\
          chmod +x ./kubectl && sudo mv ./kubectl /usr/local/bin/kubectl &&\
          kubectl version --client &&\
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 &&\
          chmod +x minikube && sudo mv minikube /usr/local/bin/minikube &&\
          minikube version &&\
          curl -Ls https://get.helm.sh/helm-v3.2.4-linux-amd64.tar.gz -ohelm.tar.gz &&\
          tar -xzvf helm.tar.gz && sudo mv linux-amd64/helm /usr/local/bin/helm &&\
          sudo chmod +x /usr/local/bin/helm &&\
          rm -rf linux-amd64 && rm helm.tar.gz &&\
          helm version &&\
          minikube start --driver=docker --kubernetes-version=v1.16.14 &&\
          kubectl get nodes &&\
          echo '{"auths":{"docker.pkg.github.com":{"auth":"'"$(echo -n "${PACKAGES_READER_GITHUB_USER}:${PACKAGES_READER_GITHUB_TOKEN}" | base64)"'"}}}' \
              | kubectl -- create secret generic github --type=kubernetes.io/dockerconfigjson --from-file=.dockerconfigjson=/dev/stdin &&\
          helm upgrade --install cwm-worker-ingress ./helm &&\
          cat tests/k8s-tests.yaml | kubectl apply -f -
          [ "$?" != "0" ] && exit 1
          ELAPSED_SECONDS=0
          while ! kubectl exec -c redis "$(kubectl get pods | grep cwm-worker-ingress | cut -d" " -f 1)" -- redis-cli ping; do
            sleep 1 && ELAPSED_SECONDS="$(expr $ELAPSED_SECONDS + 1)"
            [ "${ELAPSED_SECONDS}" == "30" ] && exit 1
          done
          kubectl exec -c redis "$(kubectl get pods | grep cwm-worker-ingress | cut -d" " -f 1)" -- redis-cli set worker:available:tests.cwm-worker-ingress.com "" &&\
          kubectl exec -c redis "$(kubectl get pods | grep cwm-worker-ingress | cut -d" " -f 1)" -- redis-cli set worker:ingress:hostname:tests.cwm-worker-ingress.com "tests.default.svc.cluster.local" &&\
          kubectl exec tests -- curl -H 'Host: tests.cwm-worker-ingress.com' http://cwm-worker-ingress | grep 'Thank you for using nginx'
        fi
