name: CI
on: [push]

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CWM_WORKER_HELM_DEPLOY_KEY: ${{ secrets.CWM_WORKER_HELM_DEPLOY_KEY }}
        HELM_VERSION: "v3.2.4"
        MINIKUBE_VERSION: "v1.21.0"
        MINIKUBE_KUBERNETES_VERSION: "v1.18.15"
        KUBECTL_VERSION: "v1.19.0"
      run: |
        bin/ci.sh

    - uses: 8398a7/action-slack@v3
      if: github.ref == 'refs/heads/master'
      with:
        status: ${{ job.status }}
        author_name: ${{ github.actor }}
        fields: all
        if_mention: success,failure
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
