name: CI
on: [push]

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CWM_WORKER_HELM_DEPLOY_KEY: ${{ secrets.CWM_WORKER_HELM_DEPLOY_KEY }}
        CWM_WORKER_CLUSTER_DEPLOY_KEY: ${{ secrets.CWM_WORKER_CLUSTER_DEPLOY_KEY }}
        HELM_VERSION: "v3.2.4"
        MINIKUBE_VERSION: "v1.21.0"
        MINIKUBE_KUBERNETES_VERSION: "v1.18.15"
        KUBECTL_VERSION: "v1.19.0"
      run: |
        curl -s "https://raw.githubusercontent.com/CloudWebManage/uumpa-ci-toolbox/main/bin/github_actions_install.sh" \
          | bash -s 807a483b65f3ec28787300499d961338a9d6bc4a CloudWebManage/uumpa-ci-toolbox
        uci github actions self-checkout --config-user-name "cwm-worker-ingress-ci"
        bin/ci.sh

    - uses: 8398a7/action-slack@v3
      if: github.ref == 'refs/heads/main'
      with:
        status: ${{ job.status }}
        author_name: ${{ github.actor }}
        fields: all
        if_mention: success,failure
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
